version: "3.1"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 8080:8085
    depends_on:
      - db
    environment:
      - PORT=8085
      - DB_URL=mysql://root:root@db/mysql
